CREATE OR REPLACE VIEW {{ database }}.GOLD.SALES_REPORT AS
SELECT ORDER_COUNT, TOTAL_AMOUNT, RULES_VERSION, RUN_TOKEN
FROM {{ database }}.GOLD.SALES_SUMMARY;
GRANT SELECT ON VIEW {{ database }}.GOLD.SALES_REPORT
    TO ROLE PROMOTION_READER_{{ environment }};