CREATE TABLE IF NOT EXISTS {{ database }}.SILVER.ORDERS (
    ORDER_ID VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    RULES_VERSION VARCHAR NOT NULL,
    RUN_TOKEN VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS {{ database }}.GOLD.SALES_SUMMARY (
    ORDER_COUNT NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    RULES_VERSION VARCHAR NOT NULL,
    RUN_TOKEN VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS {{ database }}.OPS.RELEASE_LOG (
    COMMIT_SHA VARCHAR NOT NULL,
    RULES_VERSION VARCHAR NOT NULL,
    VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    DEPLOYED_BY VARCHAR NOT NULL
);