CREATE TASK IF NOT EXISTS {{ database }}.OPS.REFRESH_ORDERS_TASK
    WAREHOUSE = PROMOTION_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS CALL {{ database }}.SILVER.REFRESH_ORDERS(FALSE);

ALTER TASK {{ database }}.OPS.REFRESH_ORDERS_TASK SUSPEND;
ALTER TASK {{ database }}.OPS.REFRESH_ORDERS_TASK SET
    WAREHOUSE = PROMOTION_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
    USER_TASK_TIMEOUT_MS = 120000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    AUTOCOMMIT = TRUE;
ALTER TASK {{ database }}.OPS.REFRESH_ORDERS_TASK MODIFY AS
    CALL {{ database }}.SILVER.REFRESH_ORDERS(FALSE);