-- Read after both environments have been deployed.
SELECT 'QA' AS ENVIRONMENT, ORDER_COUNT, TOTAL_AMOUNT, RULES_VERSION
FROM PROMOTION_QA.GOLD.SALES_REPORT
UNION ALL
SELECT 'PROD', ORDER_COUNT, TOTAL_AMOUNT, RULES_VERSION
FROM PROMOTION_PROD.GOLD.SALES_REPORT;

SELECT 'QA' AS ENVIRONMENT, COMMIT_SHA, RULES_VERSION, VALIDATED_AT, DEPLOYED_BY
FROM PROMOTION_QA.OPS.RELEASE_LOG
UNION ALL
SELECT 'PROD', COMMIT_SHA, RULES_VERSION, VALIDATED_AT, DEPLOYED_BY
FROM PROMOTION_PROD.OPS.RELEASE_LOG
ORDER BY VALIDATED_AT DESC;

SELECT STATE, SCHEDULED_TIME, COMPLETED_TIME, QUERY_ID, ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    DATABASE_NAME => 'PROMOTION_PROD', SCHEMA_NAME => 'OPS',
    TASK_NAME => 'REFRESH_ORDERS_TASK',
    SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP()),
    SCHEDULED_TIME_RANGE_END => CURRENT_TIMESTAMP(), RESULT_LIMIT => 10000))
ORDER BY SCHEDULED_TIME DESC;